name: Run test case

on: [push, pull_request]

jobs:

    run_test_case:

        runs-on: ubuntu-latest

        container:
            image: erlang:22.3

        steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-java@v1
          with:
            java-version: '8.0.x'
            java-package: jdk
        - name: Code Analysis
          run: |
            make xref
            make dialyzer
        - name: Run tests
          run: |
            make ct
            make cover
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: _build/test/logs
